### ISSUE TITLE
请问如何获取预测后的数据

### ISSUE THREAD

**Issue by lucktiner** [hichenway/stock_predict_with_LSTM#1]
非常感谢楼主，您的代码直接就能运行了，质量真棒！
想请教个问题：为什么stock_predict_1.py每次执行预测的结果都不一样呢？model_save1里的文件即使删除后重新运行也是不一样的结果。

现象：每次执行计算的next_seq值都不一样，所以预测的结果也不同
next_seq=sess.run(pred,feed_dict={X:[prev_seq]})
print ("------------->"+str(next_seq))

**Comment by hichenway** [comment]
因为每次运行神经网络的参数都重新随机初始化了，即下面的代码
``` python
weights={
         'in':tf.Variable(tf.random_normal([input_size,rnn_unit])),
         'out':tf.Variable(tf.random_normal([rnn_unit,1]))
         }
```
预测后的数据在stock_predict_1中被保存在predict数组中了，在stock_predict_2中则被保存在test_predict数组中了，你可以输出查看

**Comment by lucktiner** [comment]
明白了，谢谢！
