### ISSUE TITLE
你好，输出图我看不太懂

### ISSUE THREAD

**Issue by joyJZhang** [hichenway/stock_predict_with_LSTM#2]
你好，输出的图我不太明白
        plt.plot(list(range(len(normalize_data), len(normalize_data) + len(predict))), predict, color='r')
红色线表示normalize_data之后的预测值，对吗？但是我的形状有些奇怪，没看懂··
![wx20180123-173555](https://user-images.githubusercontent.com/23551367/35268387-f0a6474c-0063-11e8-8f27-5c3fb70ba519.png)
非常感谢！

**Comment by hichenway** [comment]
原来的代码结构有一些乱，目前代码已更新，可以查看新的代码，会更好理解

**Comment by hichenway** [comment]
你好，原来的代码结构有一些乱，目前代码已更新，可以查看新的代码，会更好理解
