### ISSUE TITLE
您好，代码运行后有个问题想请教您

### ISSUE THREAD

**Issue by ChaunceyWang4** [hichenway/stock_predict_with_LSTM#3]
ValueError: Attempt to have a second RNNCell use the weights of a variable scope that already has weights: 'sec_lstm/rnn/basic_lstm_cell'; and the cell was not constructed as BasicLSTMCell(..., reuse=True).  To share the weights of an RNNCell, simply reuse it in your second calculation, or create a new one with the argument reuse=True.

最近初学tensorflow，在博客上看到您的代码下载了运行后报了错，我在网上搜了很多方案都不行，非常困惑，恳请您能指点一下，谢谢

**Comment by CaroleHe** [comment]
Try this: 
tf.reset_default_graph()
Explore a similar question: https://stackoverflow.com/questions/47296969/valueerror-variable-rnn-basic-rnn-cell-kernel-already-exists-disallowed-did-y

**Comment by SteveXJING** [comment]
您好，第一遍跑的时候能正常出结果，但第二遍再跑的时候就出了这个问题：ValueError: Variable sec_lstm/rnn/basic_lstm_cell/kernel already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:   想请教一下该怎么处理？
