### ISSUE TITLE
iteration设置大于1的话，没有把上一次的final_state作为下一次的init_state，这样没问题么

### ISSUE THREAD

**Issue by chuanchuan12138** [hichenway/stock_predict_with_LSTM#5]
这样训练的话每个epoch就是单独训练了吧？望解答，谢谢！

**Comment by hichenway** [comment]
你好，这样做是可以的，除模型之外，还需要在训练数据的生成上也做改变，相关代码都已经更新在GitHub中了。
但是这样做的预测效果并不比之前好，个人觉得可能的原因：目前是按照batch_size = 1，也即一个一个样本训练的，这样才能让上一个样本的final_state作为下一次的init_state。但这样训练batch太小，容易过拟合。
当然，在预测的时候是把上一次的final_state作为下一次的init_state，预测结果有提升。
