### ISSUE TITLE
会不会有未来函数呢

### ISSUE THREAD

**Issue by liuwei1989** [hichenway/stock_predict_with_LSTM#9]
self.mean = np.mean(self.data, axis=0)              # 数据的均值和方差
self.std = np.std(self.data, axis=0)
self.norm_data = (self.data - self.mean)/self.std   # 归一化，去量纲

**Comment by hichenway** [comment]
你好，这里确有未来函数，因为是用的全量数据做norm，得到的是全量数据的mean和std，实际情况应该用训练数据做norm的
